version: 2

models:
  - name: silver_hosts
    columns:
      - name: host_id
        tests:
          - not_null
          - unique
  - name: silver_reviews
    columns:
      - name: listing_id
        tests:
          - not_null
      - name: review_text
        tests:
          - not_null